name: 'doxygen-with-static'
description: 'Bundling static assets into doxygen output.'
inputs:
  DOXYGEN_AWESOME_CSS_VERSION:
    description: 'The version of doxygen-awesome-css.'
    required: false
    default: 'v2.3.3'
  DOXYGEN_CONTEXT:
    description: 'Doxygen working dir.'
    required: true
  DOXYFILE:
    description: 'The path of doxyfile in PROJECT_PATH.'
    required: true
  PROJECT_PATH:
    description: 'The project path.'
    required: true
  OUTPUT_PATH:
    description: 'Doxygen output path.'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  env:
    DOXYGEN_AWESOME_CSS_VERSION: ${{ inputs.DOXYGEN_AWESOME_CSS_VERSION }}
    DOXYGEN_CONTEXT: ${{ inputs.DOXYGEN_CONTEXT }}
    DOXYFILE: ${{ inputs.DOXYFILE }}
    PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
    OUTPUT_PATH: ${{ inputs.OUTPUT_PATH }}