name: 'doxygen-with-static'
description: 'Bundling static assets into doxygen output.'
inputs:
  DOXYGEN_AWESOME_CSS_VERSION:
    description: 'The version of doxygen-awesome-css.'
    required: false
    default: 'v2.3.3'
  DOXYGEN_CONTEXT_FOLDER:
    description: 'Doxygen working dir in PROJECT_PATH.'
    required: false
    default: '/github/workspace'
  DOXYFILE:
    description: 'The path of doxyfile in PROJECT_PATH.'
    required: true
  PROJECT_PATH:
    description: 'The project path.'
    required: false
    default: '/github/workspace'
  RESOURCE_FOLDER:
    description: 'Resource dir in PROJECT_PATH'
    required: true
  OUTPUT_FOLDER:
    description: 'Doxygen output dir in PROJECT_PATH.'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  env:
    DOXYGEN_AWESOME_CSS_VERSION: ${{ inputs.DOXYGEN_AWESOME_CSS_VERSION }}
    DOXYGEN_CONTEXT_FOLDER: ${{ inputs.DOXYGEN_CONTEXT_FOLDER }}
    DOXYFILE: ${{ inputs.DOXYFILE }}
    PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
    RESOURCE_FOLDER: ${{ inputs.RESOURCE_FOLDER }}
    OUTPUT_FOLDER: ${{ inputs.OUTPUT_FOLDER }}