#!/bin/sh

echo "DOXYGEN_CONTEXT=$DOXYGEN_CONTEXT"
echo "DOXYFILE=$DOXYFILE"
echo "PROJECT_PATH=$PROJECT_PATH"
echo "OUTPUT_PATH=$OUTPUT_PATH"

DOXYFILE_PATH="$PROJECT_PATH/$DOXYFILE"

mkdir -p $OUTPUT_PATH
cd $DOXYGEN_CONTEXT
cp -r $PROJECT_PATH/static $OUTPUT_PATH/static
/usr/bin/doxygen $DOXYFILE_PATH